# Generated by Django 5.0.4 on 2024-04-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='phone_number',
            field=models.CharField(default=89999999999, max_length=20),
            preserve_default=False,
        ),
    ]
