# Generated by Django 5.0.4 on 2024-04-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_clients_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fruit', models.CharField(choices=[(1, 'Груша'), (2, 'Банан'), (3, 'Киви')], max_length=3)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
