# Generated by Django 5.0.4 on 2024-05-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=40, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures', verbose_name='Фото сотрудника')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Заработная плата')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='information',
            field=models.TextField(blank=True, verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='animal',
            name='is_rare',
            field=models.BooleanField(default=False, verbose_name='Вымирающее животное'),
        ),
        migrations.AddField(
            model_name='animal',
            name='population',
            field=models.PositiveIntegerField(default=0, verbose_name='Популяция'),
        ),
        migrations.AddField(
            model_name='animal',
            name='type',
            field=models.CharField(choices=[('mammal', 'Млекопитающее'), ('fish', 'Рыба'), ('reptile', 'Рептилия')], default='mammal', max_length=100, verbose_name='Род'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='fruit',
            field=models.CharField(choices=[('1', 'Груша'), ('2', 'Банан'), ('3', 'Киви')], max_length=3),
        ),
    ]
